# Generated by Django 6.0.5 on 2026-06-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeList', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
